﻿const Dept =[{
   id:1,
   title:"President",
   name:"President",
   head:"Hima Satwika",
   rollno:"1602-20-733-011",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/khs4",
   gmail:"satwikakatragadda444@gmail.com",
   imageSource:"https://i.postimg.cc/XN8Vjrct/president.jpg",
},
{
   id:2,
   title:"Vice President",
   name:"Vice President",
   head:"A Sathwik Reddy",
   rollno:"1602-20-734-041",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/sathwik-reddy-2b3b23215",
   gmail:"Sathwikannap03@gmail.com",
   imageSource:"https://i.postimg.cc/t46zyLnT/vice-president.jpg",
},
{
   id:3,
   title:"Head of Incubation",
   name:"Incubation",
   head:"Chandrashekar Ollala",
   rollno:"1602-20-733-076",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/chandrashekarollala/",
   gmail:"chandrashekarollala10@gmail.com",
   imageSource:"https://i.postimg.cc/j2dL3JPN/incubation.png",
},
{
   id:4,
   title:"Head of Human Resources",
   name:"Human Resources",
   head:"Hima Atluri",
   rollno:"1602-20-737-136",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/hima-atluri-10",
   gmail:"atlurihima1@gmail.com",
   imageSource:"https://i.postimg.cc/s27QMz3B/hr.jpg",
},
{
   id:5,
   title:"Head of Event Management",
   name:"Event Management",
   head:"B Lakshman",
   rollno:"1602-21-735-154",
   descrip:"",
   linkedin:"http://www.linkedin.com/in/balanakulakshman",
   gmail:"lakshmanb459@gmail.com",
   imageSource:"https://i.postimg.cc/T3Z521vM/event-management.jpg",
},
{
   id:6,
   title:"Head of Content Creation",
   name:"Content Creation",
   head:"E V Karthikeya",
   rollno:"1602-20-733-082",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/e-v-karthikeya-sri-raghavendra-1b27b9228/",
   gmail:"evkarthikeya@gmail.com",
   imageSource:"https://i.postimg.cc/GhgsNzMp/content-creation.jpg",
},
{
   id:7,
   title:"Head of Technology",
   name:"Technology",
   head:"Guru Sai Shreesh",
   rollno:"1602-20-733-079 ",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/guru-sai-shreesh",
   gmail:"guru.sai.shreesh@gmail.com",
   imageSource:"https://i.postimg.cc/tTb1PcgB/tech.jpg",
},
{
   id:8,
   title:"Head of Arts and Design",
   name:"Arts and Design",
   head:"Kotha Karthikeya",
   rollno:"1602-20-735-015",
   descrip:"",
   linkedin:"http://www.linkedin.com/in/karthikeya-kotha",
   gmail:"k.karthikeya2002@gmail.com",
   imageSource:"https://i.postimg.cc/9XJ4RJHB/content-creation-co.jpg",
},
{
   id:9,
   title:"Head of Marketing",
   name:"Marketing",
   head:"Sahil Vermuri",
   rollno:"1602-20-735-040",
   descrip:"",
   linkedin:"https://www.linkedin.com/in/sahil-vemuri-6683a8187",
   gmail:"sahilvemuri1605@gmail.com",
   imageSource:"https://i.postimg.cc/X7qrwdV6/marketing.jpg",
},
{
   id:10,
   title:"Head of Public Relations",
   name:"Public Relations",
   head:"Kriti Anchalia",
   rollno:"1602-21-735-137",
   descrip:"",
   linkedin:"http://linkedin.com/in/kritianchalia",
   gmail:"kritianchalia2@gmail.com",
   imageSource:"https://i.postimg.cc/B6CjCCL4/pr.jpg",
},
];

export default Dept;